version: '3.2'

services:

  frontend:
    container_name: frontend
    restart: always
    image: pwangdev/b2c-frontend:latest
    # volumes:
    #   - ./view/:/app
    #   - /app/node_modules
    ports:
      - "80:80"
    # command: yarn start --network-timeout 1000000


  payment:
    container_name: payment-service
    image: pwangdev/b2c-payment:latest
    restart: always
    volumes:
      # - ./payment:/payment
      - /payment/node_modules
    ports:
      - "3002:5000"

  redis_database:
    container_name: redis
    image: redis:alpine3.16
    ports:
      - "6379:6379"

  redis-server-service:
    container_name: redis-server-service
    image: pwangdev/b2c-redis-server:latest
    ports:
      - "4000:4000"
    depends_on:
      - redis_database
    environment:
      REDIS_HOST: redis_database
      REDIS_PORT: 6379